language: java
sudo: required

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
    - $TRAVIS_BUILD_DIR/libraries
env:
  - MAVEN_OPTS=-Dorg.slf4j.simpleLogger.defaultLogLevel=info mvn org.jacoco:jacoco-maven-plugin:prepare-agent $MVN_GOAL -q -fae -Dmaven.javadoc.skip=true -DfailIfNoTests=false -B -P travis

jobs:
  include:
    - stage: run_tests
      name: Run Tests
      script:
        - mvn clean test jacoco:report
        - bash <(curl -s https://codecov.io/bash)
    - stage: format_code
      name: Format Code
      script:
        - bash scripts/check_copyrights.sh
        - bash scripts/format_code.sh
        - mvn clean test
        - bash scripts/repush_formatted_code.sh
      if: branch = master AND type != pull_request