language: java
sudo: required

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
    - $TRAVIS_BUILD_DIR/libraries
env:
  - MAVEN_OPTS=-Dorg.slf4j.simpleLogger.defaultLogLevel=info mvn org.jacoco:jacoco-maven-plugin:prepare-agent $MVN_GOAL -q -fae -Dmaven.javadoc.skip=true -DfailIfNoTests=false -B -P travis

jobs:
  include:
<<<<<<< HEAD
    - stage: run_tests
=======
  - stage: run_tests
>>>>>>> a009be309e7612a2bf74cc0958f518c87544e8f4
      name: Run Tests
      script:
        - mvn clean test jacoco:report
        - bash <(curl -s https://codecov.io/bash)
    - stage: format_code
      name: Format Code
      script:
        - bash scripts/check_copyrights.sh
        - bash scripts/format_code.sh
        - mvn clean test
        - bash scripts/repush_formatted_code.sh
      only:
        - fake-master
    

# TODO: create GitHub machine user
# TODO: Figure out how to trigger formatter only AFTER merge to master
# TODO: Verify wether everything works as expected
# TODO: Gather tips&tricks for developers of how to use the formater