# Copyright FUJITSU LIMITED 2016
swagger: '2.0'
info:
  title: Event REST API
  description: API event related resources
  version: "1.0.0"

# the domain of the service
host: host_port
# array of schemes that the API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /oscm-event/v1
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  authentication:
    type: basic
    description: HTTP basic authentication with a user ID and password

security:
  - authentication: []

paths:
  /events:
    post:
      summary: Event
      description: Record an event
      parameters:
        - name: event
          in: body
          description: The event to record
          required: true
          schema:
            $ref: '#/definitions/Event'

      tags:
      responses:
        202:
          description: Accepted

definitions:
  Event:
    type: object
    properties:

      occurrenceTime:
        type: integer
        format: int64
      actor:
        type: string
      eventId:
        type: string
      multiplier:
        type: integer
        format: int64
      uniqueId:
        type: string
      technicalServiceId:
        type: string
      instanceId:
        type: string
      subscriptionKey:
        type: integer
        format: int64

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      property:
        type: string
      moreInfo:
        type: string
  