# Copyright FUJITSU LIMITED 2016
swagger: '2.0'
info:
  title: Operation Service REST API
  description: API operation related resources
  version: "1.0.0"

# the domain of the service
host: host_port
# array of schemes that the API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /oscm-operation/v1
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  authentication:
    type: basic
    description: HTTP basic authentication with a user ID and password

security:
  - authentication: []

paths:
  /settings

  get:
    description: Get all platform settings
    responses:
      200:
        description: the marketplace list
        schema:
          $ref: '#/definitions/CollectionSetting'

  post:
    description: Create a platform setting
    parameters:
      - name: setting
        in: body
        description: The setting to save
        required: true
        schema:
          $ref: '#/definitions/Setting'
    responses:
      201:
        description: Created
        headers:
          location:
            description: The id of the new setting
            type: number
            format: long

  /settings/{id}

  get:
    description: get the setting with the specified id
    parameters:
      - name: id
        in: path
        description: The id of the setting
        required: true
        type: number
        format: long
    responses:
      200:
        description: the marketplace list
        schema:
          $ref: '#/definitions/Setting'

  put:
    description: Update the specified setting
    parameters:
      - name: id
        in: path
        description: The setting id
        required: true
        type: number
        format: long
      - name: setting
        in: body
        description: The setting with the new value
        required: true
        schema:
          $ref: '#/definitions/Setting'
    responses:
      204:
        description: No content

  delete:
    description: Delete the specified setting (default value may get used afterwards)
    parameters:
      - name: id
        in: path
        description: The setting id
        required: true
        type: number
        format: long
    responses:
      204:
        description: No content

definitions:
  Setting
  type: object
  properties:
    id:
      type: integer
      format: int64
    etag:
      type: integer
      format: int64
    informationId:
      type: string
      enum:
        - AUDIT_LOG_ENABLED
        - AUDIT_LOG_MAX_ENTRIES_RETRIEVED
        - AUTH_MODE
        - BASE_URL
        - BASE_URL_HTTPS
        - CUSTOMER_SELF_REGISTRATION_ENABLED
        - DECIMAL_PLACES
        - HIDDEN_UI_ELEMENTS
        - HIDE_PAYMENT_INFORMATION
        - HTTP_PROXY
        - HTTP_PROXY_PORT
        - KEY_FILE_PATH
        - LDAP_SEARCH_LIMIT
        - LOG_CONFIG_FILE
        - LOG_FILE_PATH
        - LOG_LEVEL
        - MAIL_JA_CHARSET
        - MAX_NUMBER_ALLOWED_USERS
        - MAX_NUMBER_LOGIN_ATTEMPTS
        - MP_ERROR_REDIRECT_HTTP
        - MP_ERROR_REDIRECT_HTTPS
        - PERMITTED_PERIOD_INACTIVE_ON_BEHALF_USERS
        - PERMITTED_PERIOD_UNCONFIRMED_ORGANIZATIONS
        - PSP_USAGE_ENABLED
        - REPORT_ENGINEURL
        - REPORT_SOAP_ENDPOINT
        - REPORT_WSDLURL
        - SSO_DEFAULT_TENANT_ID
        - SSO_IDP_AUTHENTICATION_REQUEST_HTTP_METHOD
        - SSO_IDP_SAML_ASSERTION_ISSUER_ID
        - SSO_IDP_TRUSTSTORE
        - SSO_IDP_TRUSTSTORE_PASSWORD
        - SSO_IDP_URL
        - SSO_ISSUER_ID
        - SSO_LOGOUT_URL
        - SSO_SIGNING_KEY_ALIAS
        - SSO_SIGNING_KEYSTORE
        - SSO_SIGNING_KEYSTORE_PASS
        - SSO_STS_ENCKEY_LEN
        - SSO_STS_METADATA_URL
        - SSO_STS_URL
        - SUPPLIER_SETS_INVOICE_AS_DEFAULT
        - TAGGING_MAX_TAGS
        - TAGGING_MIN_SCORE
        - TIME_ZONE_ID
        - TIMER_INTERVAL_BILLING_OFFSET
        - TIMER_INTERVAL_DISCOUNT_END_NOTIFICATION_OFFSET
        - TIMER_INTERVAL_INACTIVE_ON_BEHALF_USERS
        - TIMER_INTERVAL_INACTIVE_ON_BEHALF_USERS_OFFSET
        - TIMER_INTERVAL_ORGANIZATION
        - TIMER_INTERVAL_ORGANIZATION_OFFSET
        - TIMER_INTERVAL_SUBSCRIPTION_EXPIRATION
        - TIMER_INTERVAL_SUBSCRIPTION_EXPIRATION_OFFSET
        - TIMER_INTERVAL_TENANT_PROVISIONING_TIMEOUT
        - TIMER_INTERVAL_TENANT_PROVISIONING_TIMEOUT_OFFSET
        - TIMER_INTERVAL_USER_COUNT
        - WS_TIMEOUT
    contextId:
      type: string
    value:
      type: string

  CollectionSetting:
    type: object
    description: Collection of settings
    properties:
      items:
        type: array
        items:
          $ref: '#/definitions/Setting'

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      property:
        type: string
      moreInfo:
        type: string
  